/*
	Code generated by config2go(https://github.com/xylonx/config2go)
	DON EDIT!
*/
package config

type Setting struct {
	Course struct {
		Chaoxing []struct {
			Alias    string   `mapstructure:"alias" json:"alias" yaml:"alias" `
			ClassId  int64    `mapstructure:"class_id" json:"class_id" yaml:"class_id" `
			CourseId int64    `mapstructure:"course_id" json:"course_id" yaml:"course_id" `
			Location string   `mapstructure:"location" json:"location" yaml:"location" `
			Users    []string `mapstructure:"users" json:"users" yaml:"users" `
		} `mapstructure:"chaoxing" json:"chaoxing" yaml:"chaoxing" `
		DelaySeconds    int64 `mapstructure:"delay_seconds" json:"delay_seconds" yaml:"delay_seconds" `
		IntervalSeconds int64 `mapstructure:"interval_seconds" json:"interval_seconds" yaml:"interval_seconds" `
	} `mapstructure:"course" json:"course" yaml:"course" `
	Http struct {
		AllowOrigins        []string `mapstructure:"allow_origins" json:"allow_origins" yaml:"allow_origins" `
		Host                string   `mapstructure:"host" json:"host" yaml:"host" `
		Port                int64    `mapstructure:"port" json:"port" yaml:"port" `
		ReadTimeoutSeconds  int64    `mapstructure:"read_timeout_seconds" json:"read_timeout_seconds" yaml:"read_timeout_seconds" `
		WriteTimeoutSeconds int64    `mapstructure:"write_timeout_seconds" json:"write_timeout_seconds" yaml:"write_timeout_seconds" `
	} `mapstructure:"http" json:"http" yaml:"http" `
	Location []struct {
		Alias             string  `mapstructure:"alias" json:"alias" yaml:"alias" `
		BaiduMapAddrName  string  `mapstructure:"baidu_map_addr_name" json:"baidu_map_addr_name" yaml:"baidu_map_addr_name" `
		BaiduMapLatitude  float64 `mapstructure:"baidu_map_latitude" json:"baidu_map_latitude" yaml:"baidu_map_latitude" `
		BaiduMapLongitude float64 `mapstructure:"baidu_map_longitude" json:"baidu_map_longitude" yaml:"baidu_map_longitude" `
	} `mapstructure:"location" json:"location" yaml:"location" `
	Reporter struct {
		Telegram struct {
			BotToken string `mapstructure:"bot_token" json:"bot_token" yaml:"bot_token" `
		} `mapstructure:"telegram" json:"telegram" yaml:"telegram" `
	} `mapstructure:"reporter" json:"reporter" yaml:"reporter" `
	Users struct {
		Chaoxing []struct {
			Alias  string `mapstructure:"alias" json:"alias" yaml:"alias" `
			Cookie string `mapstructure:"cookie" json:"cookie" yaml:"cookie" `
		} `mapstructure:"chaoxing" json:"chaoxing" yaml:"chaoxing" `
	} `mapstructure:"users" json:"users" yaml:"users" `
}
